version: '3'
services:
    db:
        image: mariadb
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        container_name: app-container
        build: ./Docker/php
        restart: always
        expose:
            - "9000"
            - "9001"
        volumes:
            - "./code:/app"
        links:
            - db
    webserver:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./code:/app
            - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./Docker/nginx/logs/:/var/log/nginx/
        links:
            - php
