version: '3'
services:
    db:
        image: mariadb
        restart: always
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${MYSQL_DATABASE_NAME}"
            MYSQL_USER: "${MYSQL_USER_NAME}"
            MYSQL_PASSWORD: "${MYSQL_USER_PASSWORD}"
    php:
        container_name: app-container
        build: ./Docker/php
        restart: always
        expose:
            - "9000"
            - "9001"
        volumes:
            - "./code:/app"
        links:
            - db
    webserver:
        image: nginx:alpine
        ports:
            - "${NGINX_PORT}:80"
        volumes:
            - ./code:/app
            - ./Docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./Docker/nginx/logs/:/var/log/nginx/
        links:
            - php